version: '3.8'
services:
  spleeter:
    build: .
    volumes:
      - ./input:/app/input:rw
      - ./output:/app/output:rw
      - spleeter_model:/model
    environment:
      - MODEL_PATH=/model
      - PYTHONUNBUFFERED=1
    restart: always
    tty: true
    stdin_open: true

volumes:
  spleeter_model:
